# Generated by Django 5.2 on 2025-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_crash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
