# Generated by Django 5.2 on 2025-04-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_crash', '0002_user_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
