# Generated by Django 5.2 on 2025-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_crash', '0003_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
