# Generated by Django 5.2 on 2025-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_crash', '0006_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('ONE', 'BCSCS'), ('TWO', 'BSCIT'), ('THREE', 'BCOM'), ('FOUR', 'BSSA'), ('FIVE', 'BSA'), ('SIX', 'BSS'), ('SEV', 'BSSP'), ('EIGHT', 'BSSM'), ('NINE', 'BSSN'), ('TEN', 'BSSP'), ('ELE', 'BSSM'), ('TWELEV', 'BSSN'), ('THIRT', 'BSCS'), ('FORT', 'BSIT'), ('FIFT', 'BSSE'), ('SIX', 'BSCE'), ('SEVENTN', 'BSCE'), ('EIGT', 'BSCS'), ('NINET', 'BSIT'), ('TWEETY', 'BSSE'), ('TWEETY ONE', 'BSCE')], max_length=20, null=True),
        ),
    ]
